### ISSUE TITLE
Table gives hydration error when SSR is enabled

### ISSUE THREAD

**Issue by r100-stack** [iTwin/iTwinUI#2488]
### Describe the bug (current behavior)

Noticed the following error in NextJS 15 when SSR was enabled ([sandbox](https://stackblitz.com/edit/stackblitz-starters-qvfeuclr?file=app%2FCustomTable.tsx,app%2Fpage.tsx)). Also noticed this error in React Router v7 with SSR enabled ([sandbox](https://stackblitz.com/edit/secret-python-sj3uds8j?file=app%2Fwelcome%2Fwelcome.tsx)).

Error in NextJS:

> Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:
>
> - A server/client branch `if (typeof window !== 'undefined')`.
> - Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
> - Date formatting in a user's locale which doesn't match the server.
> - External changing data without sending a snapshot of it along with the HTML.
> - Invalid HTML tag nesting.
>
> It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.
>
> See more info here: https://nextjs.org/docs/messages/react-hydration-error
>
> ```diff
>   ...
>     <div ref={function} id={undefined} role="table" style={{minWidth:0}} className="_iui3173-t..." ...>
>       <div ref={null} className="_iui3173-t...">
>         <div ref={null} className="_iui3173-t...">
>           <div ref={null} role="row" style={{display:"flex", ...}} className="_iui3173-t...">
>             <div ref={function} colSpan={1} role="columnheader" style={{...}} title={undefined} className="_iui3173-t..." ...>
>               <ShadowRoot>
>                 <ClientShadowRoot css={undefined}>
> +                 <template ref={{current:null}}>
> -                 <input className="_iui3173-checkbox" disabled="" type="checkbox" title="" tabindex="0">
>               ...
>             ...
>       ...
> ```

### Expected Behavior

No hydration errors

### Steps To Reproduce

1. Open the sandbox
2. Notice the hydration error in the console

### Package Version

- [x] I'm using the latest version of iTwinUI.

**Comment by mayank99** [comment]
I believe that the main part of this issue was fixed by #2462.

To verify: whether there is still a hydration error in `3.18.3`, and whether #2583 fixes it.

**Comment by JTBroad** [comment]
[Above example sandbox updated to 3.18.3](https://stackblitz.com/edit/stackblitz-starters-wadymobh?file=app%2FCustomTable.tsx,package.json)

@mayank99  I still see the SSR error even on 3.18.3. Let me know if there is anything else I can do to help.

**Comment by mayank99** [comment]
So it looks like #2462 fixed the hydration issue in default cells (mentioned in the issue description), and #2583 fixes _another_ hydration issue for resizers in action columns.
